### ISSUE TITLE
Pandas compatibility

### ISSUE THREAD

**Issue by VincentAntoine** [capeprivacy/cape-dataframes#112]
Hi,

I'd like to use cape-privacy in a project, however, said project runs pandas 1.2 which not compatible with cape-python's dependency constraint of `pandas~=1.0.3`.

As pandas 1.0 is now more than 1 year old, would it be possible to release a new version of cape-privacy without the version constraint on pandas (I'm assuming it works without changing anything to cape-python) ?

**Comment by gavinuhma** [comment]
Hi @VincentAntoine thanks for letting us know. We'll take a look!

**Comment by shukkkur** [comment]
@gavinuhma Any Updates ?

**Comment by shukkkur** [comment]
Solution that worked for me:
1) copied `requirements.txt`. Changed pandas & numpy versions in that file.
2) `pip install cape-privacy --no-deps`. It will install cape-privacy but without installing the requirements. 
3) `pip install -r requirements.txt`. Now we just install our version of the required packages.

**Comment by jvmncs** [comment]
This should be resolved now. In the latest release, the `install_requires` were left open to be more permissive, and we now use the newer `pip-tools`/`pip-compile` to solve the repeatable build issue which caused us to pin dependencies that way.

Also note the package has been renamed to `cape-dataframes`, which you'll want to switch to to receive any future improvements.
