### ISSUE TITLE
Documentation site is password-protected

### ISSUE THREAD

**Issue by clstaudt** [capeprivacy/cape-dataframes#120]
**Describe the bug**

Documentation site is password-protected

**Expected behavior**

Documentation of an open-source project is public.

**Screenshots**

<img width="945" alt="Screenshot 2022-01-15 at 13 49 49" src="https://user-images.githubusercontent.com/875194/149624079-629d69cf-d7f9-475b-a9cf-9e921ecda95e.png">

**Comment by jvmncs** [comment]
Documentation has moved to GitHub: https://github.com/capeprivacy/cape-dataframes/tree/master/docs
