### ISSUE TITLE
Docstrings missing in some files

### ISSUE THREAD

**Issue by StarfallProjects** [capeprivacy/cape-dataframes#86]
**Is your feature request related to a problem? Please describe.**
For the autogenerated API docs (https://docs.capeprivacy.com/pythonv1/readme/), we end up with some blank pages due to missing docstrings, and some of the pages are quite sparse on examples.

**Describe the solution you'd like**
Add the docstrings

**Describe alternatives you've considered**
Don't include the pages in the docs - let me know if that would make more sense

**Additional context**
Current blank pages:
https://docs.capeprivacy.com/pythonv1/cape_privacy.pandas/dtypes/
https://docs.capeprivacy.com/pythonv1/cape_privacy.spark/dtypes/

Current pages that could use more info/examples to bring them to the same level as similar pages:
https://docs.capeprivacy.com/pythonv1/cape_privacy.pandas/transformations/column_redact/
https://docs.capeprivacy.com/pythonv1/cape_privacy.pandas/transformations/row_redact/

**Comment by jvmncs** [comment]
The docs mentioned above have been moved to Github.
